/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    id("com.gradleup.shadow") version "8.3.5"
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name = "spigot-repo"
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        name = "papermc"
        url = uri("https://papermc.io/repo/repository/maven-public/")
    }

    maven {
        name = "sk89q-repo"
        url = uri("https://maven.enginehub.org/repo/")
    }

    maven {
        name = "jitpack.io"
        url = uri("https://jitpack.io")
    }
}

val authors = arrayOf("TheMolkaPL <themolkapl@gmail.com>")
val projectUrl = "https://github.com/Craftserve/CraftserveRadiation"
val apiVersion = "1.20"

dependencies {
    api(libs.org.bstats.bstats.bukkit)
    api(libs.org.bstats.bstats.base)
    compileOnly(libs.paper.api)
    compileOnly(libs.com.sk89q.worldedit.worldedit.core)
    compileOnly(libs.com.sk89q.worldedit.worldedit.bukkit)
    compileOnly(libs.com.sk89q.worldguard.worldguard.core)
    compileOnly(libs.com.sk89q.worldguard.worldguard.bukkit)
}

group = "pl.craftserve"
version = "1.6.2"

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(17))
}

// TODO: add publish

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}

tasks {
    shadowJar {
        archiveClassifier = null

        relocate("org.bstats", "pl.craftserve.radiation.lib.org.bstats")
    }

    processResources {
        filesMatching("plugin.yml") {
            expand(
                mapOf(
                    "projectName" to project.name,
                    "projectVersion" to version,
                    "authors" to authors,
                    "projectUrl" to projectUrl,
                    "apiVersion" to apiVersion

                )
            )
        }
    }
}
